networks:
  default:
    external: true
    name: 1panel-network

services:
  elasticsearch:
    image: bitnami/elasticsearch:8
    container_name: elasticsearch
    environment:
      - ELASTICSEARCH_ENABLE_TLS=false

      # 此配置会触发在线下载, 如果网络不可用将一直卡住, 建议移除, 手动安装需要的插件
      - ELASTICSEARCH_PLUGINS=analysis-icu
      # 禁止es自动创建`flow_metrics_`开头的索引(仅允许通过调用API手动创建该索引), 其余正常放行
      - action.auto_create_index=-flow_metrics_*,+*
    ports:
      - "9200:9200"
    volumes:
      # 挂载出来的目录需要给予ES读写权限
      - ./es-data:/bitnami/elasticsearch/data
      - ./es-plugins:/bitnami/elasticsearch/plugins
      - ./es-backup:/bitnami/elasticsearch/backup
    restart: unless-stopped

  kibana:
    image: bitnami/kibana:8
    container_name: kibana
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
    restart: unless-stopped